namespace Expresser.Core.Tokens;
public abstract record Token;
public sealed record OpeningBracket : Token;
public sealed record ClosingBracket : Token;
public abstract record Constant : Token;
public sealed record NumberConstant(double Value) : Constant;
public sealed record StringConstant(string Value) : Constant;
public sealed record BooleanConstant(bool Value) : Constant;
public record Parameter(string Name) : Token;
public record ParameterPropertyInvocation(string ParameterName, string PropertyName) : Parameter(ParameterName);
public abstract record Operator : Token;
public abstract record UnaryOperator : Operator;
public sealed record Negate : UnaryOperator;
public sealed record Not : UnaryOperator;
public abstract record BinaryOperator : Operator;
public sealed record Add : BinaryOperator;
public sealed record Subtract : BinaryOperator;
public sealed record Multiply : BinaryOperator;
public sealed record Divide : BinaryOperator;
public sealed record Or : BinaryOperator;
public sealed record And : BinaryOperator;
public sealed record GreaterThan : BinaryOperator;
public sealed record LessThan : BinaryOperator;
public sealed record GreaterThanOrEqual : BinaryOperator;
public sealed record LessThanOrEqual : BinaryOperator;
public sealed record Equal : BinaryOperator;
public sealed record NotEqual : BinaryOperator;
public abstract record Function : Token;
public sealed record MulTen : Function;